- name: Query Trex Server Ports
  import_role:
    name: roles/post_install/discover_instance_ports
  vars:
    query_instance: "{{ ansible_hostname }}"
  delegate_to: "{{ groups['undercloud'] | first }}"

- name: Parse Trex Server SR-IOV NICs
  set_fact:
    trex_instance_sriov_nics: "{{ trex_instance_sriov_nics | default([]) }} + [ {{ item }} ]"
  loop: "{{ instance_nics | flatten(levels=1) }}"
  when: item['binding:vnic_type'] == "direct-physical"

- name: Fail If There Are More/Less Than 2 SR-IOV NICs
  fail:
    msg: "Current automated flow only supports 2 SR-IOV NICs connected to intance, please provide an instance with the allowed number of NICs"
  when: trex_instance_sriov_nics | length != 2

- name: "Check if DPDK Directory Exists on  Trex Instance"
  stat:
    path: "{{ dpdk_root_dir }}"
  register: dpdk_dir
  failed_when: not dpdk_dir['stat']['exists']
  become: True

- name: Check if DPDK Compiled Binaries Directory Exists
  set_fact:
    nic_def: "{{hostvars[inventory_hostname]['ansible_default_ipv4']['alias']}}"

- name: Check if DPDK Compiled Binaries Directory Exists
  set_fact:
    nic_lst: "{{hostvars[inventory_hostname]['ansible_interfaces']}}"

- name: Check if DPDK Compiled Binaries Directory Exists
  set_fact:
    nic_down: "{{ nic_lst | difference([nic_def]+['lo'])  }}"

- name: Check if DPDK Compiled Binaries Directory Exists
  set_fact:
    nic_down: "{{ nic_down|sort() }}"

- name: Check if DPDK Compiled Binaries Directory Exists
  debug:
    var: nic_down

- name: Check if DPDK Compiled Binaries Directory Exists
  shell: "ifdown {{ item }}"
  loop: "{{nic_down}}"
  become: True

- name: Retrieve Non Active NICs' PCI Slots
  shell: "python {{ dpdk_root_dir }}/usertools/dpdk-devbind.py --status | grep -v Active | grep 0000 | cut -d ' ' -f 1"
  register: trex_instance_kernel_nics
  become: True
