---
- hosts: undercloud 
  roles:
    - role: osp/common
      port_type: 'normal'
      prefix: 'trex'
    - role: trex/install
      physical_networks: "{{ physical_network_vf }}"
      port_type: 'direct'
      prefix: 'testpmd'
    - role: trex/install
      physical_networks: "{{ physical_network_pf }}"
      port_type: 'direct-physical'
      prefix: 'trex'
    - role: images/performance
      guest_image: "{{images[0].url}}"
      delegate_to: "{{image_build_host}}"
      when:  build_image is defined and build_image|bool == True

  tasks:
    - name: Ansible Template Example
      synchronize: src="/tmp/{{ images[0].url | basename }}" dest=/tmp/
      delegate_to:  "{{image_build_host}}"
      when:  build_image is defined and build_image|bool == True
    - name: Ansible Template Example
      file: path="/tmp/{{ images[0].url | basename }}" mode='0777'
      become: true
      when:  build_image is defined and build_image|bool == True
    - name: Ansible Template Example
      local_action: template src=trex.j2  dest={{ lookup('env', 'PWD') }}/debug.trexvar.yml
