---
- name: Download images
  stat:
    path: "/tmp/{{ item.url | basename }}"
  register: st
  loop: '{{ images }}' 

- name: Download images
  get_url:
    url: "{{ item.0.url }}"
    dest: "/tmp/{{ item.0.url | basename }}"
    timeout: 100
  when: item.1.stat.isreg is not defined
  with_together:
    -  "{{ images }}"
    -  "{{ st.results }}"

- name: Upload images
  vars:
    ansible_python_interpreter: "{{ venv_path }}/bin/python"
  os_image:
    cloud: "{{ overcloud_name }}"
    name: "{{ item.name }}"
    container_format: bare
    disk_format: qcow2
    state: present
    filename: "/tmp/{{ item.url | basename }}"
    is_public: yes
  loop: "{{ images }}"
