---
- name: Gather facts
  setup:

# Delete the venv in order to avoid packages conflicts
- name: Delete existing venv if exists
  file:
    path: "{{ venv_path }}"
    state: absent
  become: true

- name: Install required packages
  vars:
    os_version: "{%- if ansible_distribution_major_version == '8' -%}
                 rhel8
                 {%- elif ansible_distribution_major_version == '7' -%}
                 rhel7
                 {%- endif -%}"
    pkg_ver_list: "{{ packages[os_version] }}"
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ pkg_ver_list | flatten(levels=1) }}"
  become: true

- name: Ensure virtualenv is present for python2 deployments
  block:
    - name: Install pip package
      easy_install:
        name: pip

    - name: Check if virtualenv is provided via RPM
      yum:
        list: python-virtualenv
      register: check_virtualenv_rpm_package

# The version of virtualenv hard coded because python 2 has issues installing latest version of dependencies for the virtualenv.
    - name: Install virtualenv from pypi if RPM is not installed
      pip:
        name: virtualenv
        version: '16.7.9'
      when: "'installed' not in check_virtualenv_rpm_package | json_query('results[*].yumstate')"
  become: True
  when: hostvars[groups['undercloud'][0]]['ansible_python']['version']['major'] == 2

# A pip bug prevents us to use the pip module for the python3 venv creation.
# Remove when fixed.
# Reference: https://github.com/ansible/ansible/issues/52275
- name: Install venv if python3 present
  command: "{{ ansible_python.executable }} -m venv {{ venv_path }}"
  when: ansible_python.version.major == 3

# Install pip and setuptools should happen before other rpackages
- name: Install virtualenv core deps
  pip:
    name:
      - pip>=10.0.1
      - setuptools>=39.0.0
    virtualenv: "{{ venv_path }}"

- name: Install virtualenv packages
  pip:
    name:
      - pytz==2016.4
      - cmd2==0.8.6
      - shade>=1.25
    virtualenv: "{{ venv_path }}"

- name: Generate clouds.yaml file
  import_tasks: clouds.yml
