---

- block:
    # Delete the venv in order to avoid packages conflicts
    - name: Delete existing venv if exists
      vars:
        ansible_python_interpreter: /usr/libexec/platform-python
      file:
        path: "{{ venv_path }}"
        state: absent

    - name: Install requirements for pip virtualenv
      vars:
        ansible_python_interpreter: /usr/libexec/platform-python
        os_version: "{%- if hostvars[groups['undercloud'][0]].ansible_distribution_major_version == '8' -%}
                     rhel8
                     {%- elif hostvars[groups['undercloud'][0]].ansible_distribution_major_version == '7' -%}
                     rhel7
                     {%- endif -%}"
        pkg_ver_list: "{{ packages[os_version] }}"
      package:
        name: "{{ item }}"
        state: present
      loop: "{{ pkg_ver_list | flatten(levels=1) }}"
  become: true

- name: Install venv if python2 present
  block:
    - name: Install pip package
      easy_install:
        name: pip

    - name: Install virtualenv
      pip:
        name: virtualenv
        version: '15.1.0'
  become: True
  when: hostvars[groups['undercloud'][0]]['ansible_python']['version']['major'] == 2

# A pip bug prevents us to use the pip module for the python3 venv creation.
# Remove when fixed.
# Reference: https://github.com/ansible/ansible/issues/52275
- name: Install venv if python3 present
  command: "{{ ansible_python_interpreter }} -m venv {{ venv_path }}"
  vars:
    ansible_python_interpreter: /usr/libexec/platform-python
  when: hostvars[groups['undercloud'][0]]['ansible_python']['version']['major'] == 3

- name: Install venv packages
  vars:
    ansible_python_interpreter: /usr/libexec/platform-python
  pip:
    name:
      - pip>=10.0.1
      - setuptools>=39.0.0
      - pytz>=2017.3
      - shade>=1.25.0
    virtualenv: "{{ venv_path }}"

- name: Fetch private key from the undercloud host
  vars:
    ansible_python_interpreter: /usr/libexec/platform-python
  fetch:
    src: "/home/stack/.ssh/id_rsa"
    dest: "{{ overcloud_private_key }}"
    flat: yes

- name: Set SSH key permissions
  file:
    path: "{{ overcloud_private_key }}"
    mode: 0600
  delegate_to: localhost

- name: Grab auth data from stackrc file and publish it as YAML
  ### ToDo(MaximB): Convert the task to more generic execution.
  ###               Implement reuse.
  vars:
    ansible_python_interpreter: /usr/libexec/platform-python
  shell: |
      source "{{ rc_file_path | default('/home/stack/stackrc') }}"
      echo "
      auth_url: $OS_AUTH_URL
      username: $OS_USERNAME
      password: $OS_PASSWORD
      project_name: ${OS_PROJECT_NAME:-$OS_TENANT_NAME}
      user_domain_name: ${OS_USER_DOMAIN_NAME:-''}
      project_domain_name: ${OS_PROJECT_DOMAIN_NAME:-''}
      "
  register: creds

- name: Gather Overcloud nodes data
  vars:
    ansible_python_interpreter: "{{ venv_path }}/bin/python"
  os_server_facts:
    auth: "{{ creds.stdout | from_yaml }}"
    # Required for SSL
    validate_certs: no

- name: Set the path to download the overcloud switft container
  set_fact:
    overcloud_swift_path: "/tmp/swift_container"

- name: Create directory to download overcloud swift container
  file:
    state: directory
    path: "{{ overcloud_swift_path }}"

- name: Get the plan-environment file
  file: path="{{ overcloud_swift_path }}/plan-environment.yaml" state=absent

- name: Get the plan-environment file
  shell: |
    source "{{ rc_file_path | default('/home/stack/stackrc') }}"
    openstack container save overcloud
  args:
    chdir: "{{ overcloud_swift_path }}"
    creates: "{{ overcloud_swift_path }}/plan-environment.yaml"

- name: Fetch the plan-environment file
  slurp:
    src: "{{ overcloud_swift_path }}/plan-environment.yaml"
  register: plan_content

- name: Parse the plan-environment content
  set_fact:
    plan: "{{ plan_content.content|b64decode|from_yaml }}"
  no_log: true

- name: Extract required variables from plan-environment
  set_fact:
    bridge_mappings_tmp: "{{ plan.parameter_defaults.NeutronBridgeMappings|default('') }}"
    vlan_ranges_tmp: "{{ plan.parameter_defaults.NeutronNetworkVLANRanges|default('') }}"
    dns_nameservers: "{{ plan.parameter_defaults.DnsServers|default('') }}"
    flat_net_tmp: "{{ plan.parameter_defaults.NeutronFlatNetworks|default('') }}"
    extern_def_route: "{{ plan.parameter_defaults.ExternalInterfaceDefaultRoute }}"
    extern_net_cidr: "{{ plan.parameter_defaults.ExternalNetCidr }}"
    extern_pool_end: "{{ plan.parameter_defaults.ExternalAllocationPools[0].end }}"
    phy_dev_map: "{{ plan.parameter_defaults.NeutronPhysicalDevMappings|default('') }}"
